### ISSUE TITLE
Sing-Box PR

### ISSUE THREAD

**Issue by alidxdydz** [redpilllabs/redpilllabs.github.io#1]
سلام دوست عزیز.
شرمنده اگه تو مخزن نامربوطی Issue نوشتم.

بابت [PR فرگمنت](https://github.com/SagerNet/sing-box/pull/1150) که برا [هسته sing-box](https://github.com/SagerNet/sing-box) زدید، واقعا از شما ممنونم. متاسفانه بنظر دولوپر اصلی sing-box همین رویه بد رو نسبت به همه داره و یکی از دلایل ایجاد [هسته sing-box-extra](https://github.com/MatsuriDayo/sing-box-extra) همینه.

[MatsuriDayo - Telegram Comment](https://t.me/MatsuriDayo/196)
[MatsuriDayo - Telegram Comment](https://t.me/MatsuriDayo/197)

اخیرا روش فرگمنت تو این [Issue](https://github.com/net4people/bbs/issues/308) بطور مفصل بحث شد که بنظر میاد حتی تو بعضی از شهرهای چین هم کار میکنه.
برا همین میخواستم از شما خواهش کنم که امکان اضافه کردن این قابلیتو به [sing-box-extra](https://github.com/MatsuriDayo/sing-box-extra) یا هسته کلاینت هدیفای ([hiddify-sing-box](https://github.com/hiddify/hiddify-sing-box) و [hiddify-next-core](https://github.com/hiddify/hiddify-next-core)) بررسی کنید تا هم زحمت شما حیف نشه و هم کاربرا از این قابلیت استفاده کنن.

**Comment by kyochikuto** [comment]
با @hiddify در تماس هستم برای پیاده سازی اما تمایلی به مشارکت در مخازن چینی ندارم مگر اینکه مولف اصلی شخصا ازم درخواست کنه.
